# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1892eadd640cb552f3c6108541c7a1c3823bac485468ff736262e1dfbbb1fdd7fc162dd9d4145eb0e5a74baf9944fd7d036083b4ee4f5e6444bd499f3f0dca5a

test:
  secret_key_base: ba3f454f0bb2dd2fcad8495c360bcd139fb6f3f5ca4b253f1c604f415378d1a35aabfe65df459b610fe57366fa876c99974b8099534837538c4ed648dbd8a68e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
